spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.96.130:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password:

    root: warn
    com.star: info
  file: log/blog-pro.log

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB



  thymeleaf:
    prefix=classpath: /templates

mybatis:
  type-aliases-package: com.star.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8085




